#!/bin/sh
# usage: fsplit file1 file2
total=0; lost=0
while read next
do
total=`expr $total + 1`
case "$next" in
    *[A-Za-z]*)  echo "$next" >> $1 ;;
    *[0-9]*)     echo "$next" >> $2 ;;
    *)           lost=`expr $lost + 1`
esac
done
echo '$total lines read, $lost thrown away'

#!/bin/sh
# usage: process sub-directory
dir=`pwd`
for i in *
do
if test -d $dir/$i
then
    cd $dir/$i
    while echo "$i:"
    read x
    do
        eval $x
    done
    cd ..
fi
done
